#!/usr/bin/php
<?php
/*

Name: 	scrobble.php
Author: Alex Wilson

Syntax: ./scrobble.php "<artist>" "<track>"

A script to scrobble (add to last.fm "Played" list) the music played during LANs.
*/

define(API_KEY, '');	//API Key for Last.fm
define(SEKRIT, '');	//Your API Secret, comes with the above.
define(NAME, '');	//Last.fm username
define(PWD, '');	//Last.fm password for the above account

//Generate authorisation key for auth.getMobileSession
$auth = md5(utf8_encode(NAME.md5(utf8_encode(PWD))));

//Generate method signature for auth.getMobileSession.
$sig = md5(utf8_encode(
	"api_key".API_KEY.
	"authToken".$auth.
	"methodauth.getMobileSession".
	"username".NAME.
	SEKRIT)
);

//Generate URL where we'll get the session identifier.
$url=	'http://ws.audioscrobbler.com/2.0/'.
	'?format=json'.
	'&method=auth.getMobileSession'.
	'&api_key='.API_KEY.
	'&api_sig='.$sig.
	'&username='.NAME.
	'&authToken='.$auth; 

//Follow URL. Recieve Token.
$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL,$url); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER,true);
$return = curl_exec($ch);

//Array with parameters drawn from cmd-line arguments.
$paras = array (
	"track"  => preg_replace("/\\\\'/","'",$argv[2]), 	//If the track name or artist has single quotes in their name, this removes the escapes necessary in bash
	"artist" => preg_replace("/\\\\'/","'",$argv[1]),
	"method" => "track.scrobble",
	"timestamp" => time(),
	"sk" => json_decode($return)->{'session'}->{'key'},
	"api_key" => API_KEY
);

scrobble($paras);	//Scrobble to last.fm

function scrobble($data) {

	ksort($data);	//Sort the scrobbling array by key. Last.fm is strict about this.
	$sig = "";

	foreach($data as $k => $v) {
		$sig .= $k.$v;
	}
	
	$sig .= SEKRIT;
	$sig = md5($sig);
	$data["api_sig"] = $sig;	//Method signature generated, add to $data.

	$dataString = "";
	
	foreach ($data as $l => $j) {
		$dataString .= $l."=".$j."&";
	}
	
	$dataString .= "format=json";	//Put all of $data into an appropriate string.

	$scr = curl_init();
	curl_setopt($scr, CURLOPT_URL,"http://ws.audioscrobbler.com/2.0");       
	curl_setopt($scr, CURLOPT_HEADER, 0);
	curl_setopt($scr, CURLOPT_RETURNTRANSFER,true);
	curl_setopt($scr, CURLOPT_POSTFIELDS, $dataString);
	curl_setopt($scr, CURLOPT_POST, count($data));
	
	curl_exec($scr);	//Scrobbled...
	curl_close($scr);	//...and done

	
}
?>
